# Generated by Django 2.2 on 2021-02-02 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20210202_1032'),
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='has_created_list', to='login_reg_app.User'),
            preserve_default=False,
        ),
    ]
